#This is for learning
setwd("C:/Users/raymond.odinoh/OneDrive - Washington State University (email.wsu.edu)/RVF/Analysis/Analysis2")
library(tidyverse)
library(janitor)
library(dplyr)
library(tidylog)
library(lubridate)
library(REDCapR)
library(readxl)
library(readr)
library(plyr)
library(data.table)
library(gt)
pacman::p_load(easystats) # forest plot
library(broom)
library(gtsummary)
library(gt)
library(VIM)
library(reshape2)
library(mice)
library(sjlabelled) 
library(data.table)
library(officer)
library(flextable)